---
title: "Curriculum Vitae"

---


## Education



#### **University of California, Santa Barbara**  *2018-2020*
<center>
#### Environmental Studies B.S.

* GPA- 3.91 
* Environmental Studies Program-Outstanding Academic Achievement Award
* 6x Dean's List

#### **College of San Mateo**  *2016-2018*
* GPA- 3.92

****
****

## Experience

#### **Undergraduate Teaching Assistant** *July 2020 - September 2020*
###### -  **ENV S 115, Energy and The Environment**, *UC Santa Barbara*
* Assists Professor Lovering, PhD, with proof reading assignments
* Grades homework, tests, and quizzes

#### **Undergraduate Research Assistant** *September 2019 - March 2020* 
###### - **PISCO LAB**, *UC Santa Barbara* 

* Partnership for Interdisciplinary Studies of Coastal Oceans (PISCO), run by Dr. Jennifer Cassele
* Collected and implemented samples in the field and analyzed data in the lab

#### **Student Summer Researcher** *June 2019 - September 2019*
###### **UCSF Benioff Children's Hospital**, *Oakland, California*
* Conducted a study on femoral shaft fractures under the guidance of Dr. Coleen Sabatini, MD, MPH
* Gathered and compiled data from medical records in addition to shadowing an orthopaedic surgeon daily
* Currently working on publishing a manuscript of the research, findings from the study disagree with the current
metrics used by US News and World Report to evaluate orthopaedic programs

#### **Exhibit Interpreter** *September 2018 - May 2019*
###### **Santa Barbara Museum of Natural History Sea Center**, *CA*
* Educated museum visitors about the marine ecosystems found in the local ocean waters
* Introduced the public into the research done at the Sea Center, such as species collection

****
****
## Activities
* UCSB Club Baseball - 1^st^ Team All Region
* Member of UCSB Clean Energy Tranformation Lab
* Intercollegiate Baseball at College of San Mateo
