---
title: "Projects"
---

## UCSB Research and Course Work
  All Work Done Through R Studio and ArcMap Pro
 
****


### Project 1
### [COVID-19 Data Analysis](https://jacobbraslaw.github.io/geog-176A-labs/lab-02.html)
- Found "safe" counties in California
- Found highest cumulative, daily new, and 7 day rolling average of cases by county
- Look at state level data in total cases and per capita

****

### Project 2
### [U.S Border Statistics](https://jacobbraslaw.github.io/geog-176A-labs/lab-03.html)

- Looks at areas and populations within 100 miles from any US Border
- Majority of Americans live within 100 miles of the national border
- Identify every city in which US Border Patrol has jurisdiction

**** 
### Project 3
### [Wind Turbine Power Density Analysis](https://www.linkedin.com/feed/update/urn:li:activity:6680312682991747072/)
- Determined the effect of land factors on power density (w/m^2^) of wind turbines with regression analysis
- From analysis, located ideal place to construct future wind turbine facility to meet needs of Kern County

****
### Project 4
### [Arizona Solar Panels](https://storymaps.arcgis.com/stories/5b465fe567d24cd2959fbd4d54a4fd38) 
- Based on data layers from electrical grids, wildlife, DEM, solar radiation, and cities a solar suitabilty map was generated.
- Ideal location for photovoltaic panels was determined based upon the generated suitability data layer.

****
### Project 5
### [US National Dam Tessalations](https://jacobbraslaw.github.io/geog-176A-labs/lab-04.html)

- Look at different tessalations of US County lines to identify modifiable arial unit problems
- Analysis on dams to find where the highest dam counts are based on uses of dams

****
### Project 6
### [Raster Flood Analysis](https://jacobbraslaw.github.io/geog-176A-labs/lab-05.html)

- Looked at landsat imagery 
- Remote sensing analysis to discover where flooded land was in Palo, Iowa


